hydra:
  run:
    # dynamic output directory according to running time and override name
    dir: outputs_xpinn/${now:%Y-%m-%d}/${now:%H-%M-%S}/${hydra.job.override_dirname}
  job:
    name: ${mode} # name of logfile
    chdir: false # keep current working direcotry unchaned
    config:
      override_dirname:
        exclude_keys:
          - TRAIN.checkpoint_path
          - TRAIN.pretrained_model_path
          - EVAL.pretrained_model_path
          - mode
          - output_dir
          - log_freq
  sweep:
    # output directory for multirun
    dir: ${hydra.run.dir}
    subdir: ./

# general settings
mode: train # running mode: train/eval
seed: 134
output_dir: ${hydra:run.dir}
log_freq: 20

# model settings
MODEL:
  num_ub: 200 # Boundary points from subdomain 1
  num_f1: 5000 # Residual points in three subdomains
  num_f2: 1800
  num_f3: 1200
  num_i1: 100 # Interface points along the two interfaces
  num_i2: 100
  layers1: [2, 30, 30, 1]
  layers2: [2, 20, 20, 20, 20, 1]
  layers3: [2, 25, 25, 25, 1]

# set training data path
TRAIN_DATA_DIR: "./data/XPINN_2D_PoissonEqn.mat"

# training settings
TRAIN:
  epochs: 501
  iters_per_epoch: 1
  save_freq: 50
  eval_during_train: true
  eval_freq: 50
  learning_rate: 0.0008
  batch_size: 4
  pretrained_model_path: null
  checkpoint_path: null

# evaluation settings
EVAL:
  batch_size: 1
  pretrained_model_path: null
  eval_with_no_grad: false
